version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: reserve-backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: ./reservation-app/Dockerfile
    container_name: reserve-frontend
    env_file:
      - ./reservation-app/.env
    ports:
      - "3000:3000"

volumes:
  mysql_data:
